name: notecard_env_var_manager CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run unit tests
        uses: ./.github/actions/run_unit_tests
  run_astyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install astyle
        run: sudo apt-get install -y astyle
      - name: Check formatting
        run: ./scripts/run_astyle.sh
